### ISSUE TITLE
6.10.1 isn't loading on iPad 

### ISSUE THREAD

**Issue by frankjonen** [javalent/admonitions#172]
Unlike the previous Admonition version this fails to load on the current iPad version (1.0.5).

**Comment by valentine195** [comment]
Hmm, it loads fine on my iPhone.

what iOS version are you on?

**Comment by frankjonen** [comment]
`12.5.5` I haven't changed the iOS version but updated the plug-in. That's the only thing changed. Now I get the loading error.

**Comment by valentine195** [comment]
Have you updated the Obsidian app lately?

**Comment by frankjonen** [comment]
Nope. I'm not updating Obsidian on the desktop anymore. The mobile app is far enough behind as it is already. The only change I made was updating Admonition. Had a similar issue with [Dataview](https://github.com/blacksmithgu/obsidian-dataview/issues/784) when that got updated. It was loading though but most of the stuff isn't working anymore on iPad. Might be related, might not be.

**Comment by valentine195** [comment]
Okay, this is likely an app versioning issue then. I use some new features from Obsidian v0.13.14+ (desktop... not sure how that maps to the mobile version). I updated my versioning file to reflect this, but you'll likely have to downgrade your Admonitions install.

**Comment by frankjonen** [comment]
Found the last version that still works on iOS: `6.9.5`
Maybe that helps diagnosing.

**Comment by valentine195** [comment]
I _believe_ that this issue should be resolved with the latest Obsidian Mobile public release. Can you confirm?

**Comment by frankjonen** [comment]
Just tested it. Nope. Need to roll back when I get back to the desktop. For now my files look like a mess again. 

![4090936B-B810-404B-95CB-DA7B572E1EF5](https://user-images.githubusercontent.com/3016983/155380454-46175a1a-f1df-44d9-b660-90e5fdd37b68.jpeg)

**Comment by frankjonen** [comment]
Certainly weird. For me it stopped after 6.9.5.

Here's my data file. But after the last update problems (update > didn't work > delete > unzip 6.9.5 > copy back ) I left everything on default as I've always deleted the plug-in folder each time anyway.

[data.json.zip](https://github.com/valentine195/obsidian-admonition/files/8128563/data.json.zip)

**Comment by valentine195** [comment]
Does this still occur?

**Comment by frankjonen** [comment]
I just installed it again. 
Install went fine but tapping on `Enable` yielded the same error yet again. 🤷‍♂️

**Comment by sigrunixia** [comment]
@frankjonen This may seem like a redundant ask, but I am checking if this is still an issue. There has been quite a few major Obsidian updates since then on iPadOS that have improved the rendering of code blocks, and our ability to diagnose those issues have been improved as a result.

**Comment by frankjonen** [comment]
@sigrunixia Thanks for checking. I've moved on from Admonitions to Obsidian's native ones with some own CSS extensions (custom terms).
