### ISSUE TITLE
Bug: Admonition sometimes appears twice when you edit it later (only in live preview mode, not reading mode)

### ISSUE THREAD

**Issue by ReaderGuy42** [javalent/admonitions#202]
I have a admonition block, that I returned to a few minutes after creating, and added another sentence. Now the admonition appears twice, once as it originally was, and once with the new addition. This does not show up in reading mode. 
And when you click "Edit this block" it's also only a single codeblock.

This does not always happen, so it's difficult to reproduce.

**Comment by valentine195** [comment]
Is it a block quote or code block?

**Comment by ReaderGuy42** [comment]
Both. I think the issue occurred when I put a `>` in the code block.

**Comment by sigrunixia** [comment]
@ReaderGuy42 Are you still having this issue?

**Comment by ReaderGuy42** [comment]
Honestly, I can't even remember this bug. I haven't used admonitions that much since then, but I guess I also haven't found this bug still. Thanks though.
