### ISSUE TITLE
Markdown syntax highlighting in admonition code blocks is semi-broken in Obsidian v0.13.30 and v0.13.31

### ISSUE THREAD

**Issue by EHBaozi** [javalent/admonitions#213]
Behavior in v0.13.30 and v0.13.31:

![图片](https://user-images.githubusercontent.com/38034505/157739348-273526df-e405-4274-a3ba-0d46f17833d6.png)

In v0.13.23:

![图片](https://user-images.githubusercontent.com/38034505/157739558-2037068e-b697-4f08-9169-3dc582a33f5b.png)

So the syntax highlighting is still there, but more similar to the old editing mode. Also math formulas are no longer rendered inside the admonition block.

**Comment by valentine195** [comment]
Is this in live preview?

**Comment by sigrunixia** [comment]
@EHBaozi 

Are you still experiencing this issue?
