### ISSUE TITLE
Duplicated icons when using Icon Shortcodes in admonitions

### ISSUE THREAD

**Issue by corinnekaryiu** [javalent/admonitions#225]
I originally posted this issue on the Icon Shortcodes plugin page (aidenlx/obsidian-icon-shortcodes#37), but it seems like it might be related to the Admonition plugin.

If I add an icon shortcode into an admonition, the icon is added twice.

For example, the code below:

```
> [!info:]
> - :fas_running: [[Activities]]
> - :far_calendar_plus: [[Planner]]
> - :fas_dumbbell: [[Gym Timetable]]

:fas_running: [[Activities]]
:far_calendar_plus: [[Planner]]

- :fas_dumbbell: [[Gym Timetable]]

> :fas_running: [[Activities]]
```

Displays like this:

![image](https://user-images.githubusercontent.com/100031232/158959657-867ae004-0364-4b32-8fdc-8b3b9bf40720.png)

At the moment I'm using CSS to hide the second icon, but it would be great if this could be fixed. I understand that the icons work correctly for the new callouts, but I don't yet have access to those.

**Comment by sigrunixia** [comment]
This should be resolved as the issue was pertaining to the updating rendering of callouts. If the issue is persisting, a new thread can be created.
