### ISSUE TITLE
Nesting Custom Callouts: the setting "No Admonition Title by Default" seems to be ignored when using the native Obsidian Callouts syntax  

### ISSUE THREAD

**Issue by I-Pch** [javalent/admonitions#229]
Hi there again 😊 !

I'm trying to create nested custom callouts (i.e.: admonitions used with the native Obsidian Callouts Syntax) but, for some reasons,  the setting `No Admonition Title by Default` seems to be ignored for the nested custom callout which therefore, renders the type/title of the custom callout even with `No Admonition Title by Default` toggled `ON`... 

## Test Environment
- Mac (Big Sur 11.6.5)
- Obsidian v0.14.2
- Admonition 8.2.3
- No Community Theme 

#### 1. `> [!nav]`
(the setting `Admonition Title` is empty)
<img width="741" alt="nav" src="https://user-images.githubusercontent.com/77828085/159274144-0c6304b8-18cd-4063-bec7-5e0cf5c0b3cd.png">

#### 2. `> [!ephemeris]`
(the setting `Admonition Title` is also empty)
<img width="741" alt="ephemeris" src="https://user-images.githubusercontent.com/77828085/159274382-98fcb72f-2e54-432e-9f5c-df3c15858ad5.png">

## Test 1: Used one after the other in a note
```
> [!nav]
> Here's the `[!nav]` custom callout

> [!ephemeris]
> Here's the `[!ephemeris]` custom callout
```
#### 🟢 Result
They are rendered in `LP` and `Reading` as desired (no icon, type/title) as I didn't precise any title and didn't make them collapsable...
<img width="664" alt="Nav and Eph - LP" src="https://user-images.githubusercontent.com/77828085/159277178-91cd4135-75d3-4c44-8c31-7bcf8abc82a0.png">

## Test 2: Nesting `[!ephemeris]` within `[!nav]`
```
> [!nav]
> Here's the `[!nav]` custom callout
> 
> And another "Custom Callout"
> > [!ephemeris]
> > Here's the `[!ephemeris]` custom callout
> 
> Back to `[!nav]` ...
```
#### 🟠 Result
The toggled `ON` setting for `No Admonition Title by Default` of `[!ephemeris]` seems to be ignored but it still works for the 1st level custom callout `[!nav]`.
 
<img width="664" alt="Nested ephemeris within nav - LP" src="https://user-images.githubusercontent.com/77828085/159280168-3582e577-bb82-4a8b-b389-a248585a3754.png">

## Expected result
Nesting `[!ephemeris]` within `[!nav]` using the native Obsidian callout syntax, I was hoping to get the same result I can get in `Reading` when nesting them using the Admonition code block syntax 😊 .  
<img width="661" alt="Nested code block Admonitions - Reading" src="https://user-images.githubusercontent.com/77828085/159281063-9db2c22a-97b8-4899-a4f1-2522f05bebc3.png">

I don't know if this would be feasible but maybe there could be a way to force the `No Admonition Title by Default` for the nested custom callouts to be taken into account by Obsidian ? 🤔 

Couldn't this setting be added to the Admonition CSS snippet so it potentially overrides the Obsidian callout CSS ? 😇

I have no idea how to do that 😅 ... hence why I'm here 😊...

 I'm sorry for the length 😇 ... But I thank you very much in advance for any help 😁 !

**Comment by Cammagno** [comment]
> I don't know if this would be feasible but maybe there could be a way to force the `No Admonition Title by Default` for the nested custom callouts to be taken into account by Obsidian ?

Same issue for me, and same wish :)

**Comment by Aradoexis** [comment]
I have this problem too.
