### ISSUE TITLE
[Bug] Export custom types as css button not working on mobile

### ISSUE THREAD

**Issue by Obsidian1212** [javalent/admonitions#237]
![Screenshot_20220329-095348_Obsidian Insider](https://user-images.githubusercontent.com/35908303/160516781-05f0970d-3aca-42bd-8423-9cfdc2dffcec.jpg)

![Screenshot_20220329-095618_Obsidian Insider](https://user-images.githubusercontent.com/35908303/160516991-cb4cbf1f-9fcf-49ce-9f30-87565e4489f6.jpg)

Absolutely nothing happens when you click onto that button.

App: Latest mobile insider (50)
System: Android 11, Samsung Galaxy S21 Ultra

**Comment by sigrunixia** [comment]
@Obsidian1212 

Hello, are you still having issues exporting custom CSS on Mobile? How about .Json files as well?

**Comment by Obsidian1212** [comment]
Yup, still not working. The import button crashes the entire Obsidian app as well... Might need to report to the devs.

**Comment by Obsidian1212** [comment]
There's none on the surface. Not sure about the console though.

Also, here's a screencap.

https://user-images.githubusercontent.com/35908303/234155730-2605f50e-136e-4f20-8378-996fcecaae65.mp4
