### ISSUE TITLE
Admonition to Callout conversion converts block MathJax equations to in-line

### ISSUE THREAD

**Issue by anzhulin** [javalent/admonitions#238]
When converting Code Block Admonitions to Callouts, equations embedded in $$...$$ split across multiple lines becomes $...$ and is then rendered incorrectly.

Code Block Admonition: 
![image](https://user-images.githubusercontent.com/19489369/160759428-3aa8dcfc-d8c0-4944-a4d0-48f4a2f3369b.png)
Converted to Callout:
![image](https://user-images.githubusercontent.com/19489369/160759570-c0bc8fa4-5e1b-4394-8f52-9e6497657465.png)

**Comment by J-MR-T** [comment]
I would really like to see this fixed, I'm running into the same issue

**Comment by sigrunixia** [comment]
@J-MR-T and @anzhulin Are you both experiencing issues with this still?

**Comment by J-MR-T** [comment]
At the moment, I have just accepted the old codeblock syntax as legacy code in my vault, but I'll test it again later today, thanks for your interest in solving this :).

**Comment by J-MR-T** [comment]
Sorry, lost track of this, but now I've tested it, and the issue persists (the text is in german here, but the problem should be obvious regardless of the text :

Original 'legacy' callout codeblock:

```md
```ad-note
title: Definition: Example
1. A set: $\Omega=\set{\omega_1,\omega_2,\dots}$.
2. Every element $\omega_i$ gets a probability: $\Pr[\omega_i]$, we require $0\leq \Pr[\omega_i]\leq 1$ and
	$$
	\sum_{\omega\in\Omega}\Pr[\omega]=1
	$$
\```
```

Rendered:
![image](https://user-images.githubusercontent.com/40471097/235298759-9dcddcbc-2f25-4fcc-9d85-0b391f884752.png)

Converted:

```
> [!note] Definition: Example
> 1. A set: $\Omega=\set{\omega_1,\omega_2,\dots}$.
> 2. Every element $\omega_i$ gets a probability: $\Pr[\omega_i]$, we require $0\leq \Pr[\omega_i]\leq 1$ and
> 	$
> 	\sum_{\omega\in\Omega}\Pr[\omega]=1
> 	$
```

![image](https://user-images.githubusercontent.com/40471097/235298827-47600884-c8dd-4e1f-8afa-9f9804a6b169.png)

The $$ environment gets converted to a single $.

**Comment by sigrunixia** [comment]
No problem on the delay and thank you! This is very helpful!
