### ISSUE TITLE
[Command not work] Open/Collapse Admonitions in Note

### ISSUE THREAD

**Issue by JustusPan** [javalent/admonitions#245]
I have created several foldable Admonition format callout in a note. And try to use `Open Admonitions in Note` before I export it to PDF.
But then I find both of Open and Collapse commands didn't work.

Obsidian 0.14.6

**Comment by JustusPan** [comment]
```ad-info
icon: ra-aware
title: test-title
collapse: open
test content
```

this is my block

**Comment by calegox** [comment]
I'm finding that the "collapse: open" is not working in my admonition notes.  The note always appears collapsed upon the note opening, even though the "collapse: open" is supposed to have it default to open state when the note is opened.

**Comment by sigrunixia** [comment]
@JustusPan and @calegox are either of you experiencing this issue still?

**Comment by sigrunixia** [comment]
After extensive testing, I am unable to recreate this issue so assuming it is fixed. If this issue appears again, a new thread can be created.
