### ISSUE TITLE
costomize admontion - obsidian android-app - color

### ISSUE THREAD

**Issue by frankmill** [javalent/admonitions#246]
with google-translate: 

yes, you can also set colors in the app, but unfortunately imprecisely with sliders;  

you cannot overwrite them either;  

what is missing is a function for setting the colors using rgb or hex values.  
You can find that everywhere else, why not here?

**Comment by frankmill** [comment]
Hello sigrunixia,
first of all thank you very much for the implementation.

This is already a big help.
I now create the callouts on the desktop version save them in a .md, which I then transfer to my tablet. There then copy and paste.

However, it would be more convenient if the now provided feature was also integrated mobile.
Maybe it can be inserted on occasion.

I don't have it yet with the css-snippets under Obsidian out.

This is already a big help.
I now create the callouts on the desktop version save them in a .md, which I then transfer to my tablet. There then copy and paste.

However, it would be more convenient if the now provided feature was also integrated mobile.
Maybe it can be inserted on occasion.

I don't have it yet with the css-snippets under Obsidian out.

**Comment by valentine195** [comment]
The plugin uses the native color picker. Your browser determines what you can input. I believe Obsidian on Android uses Chrome for Android. I am surprised that it does not offer this. 

However, I will not be changing color pickers.
