### ISSUE TITLE
Callout custom colors do not work

### ISSUE THREAD

**Issue by feedhopper** [javalent/admonitions#252]
First of all: GREAT plugin, great functionality, great that it's been implemented in Obsidian.

Unfortunately, using the callout function does not properly  work for me - custom colors default to blue, and the note icon is shown instead of the one I picked - even though the custom title is inserted.

In admonition mode, the custom colors are rendered properly
Is there any chance to fix this? I would much prefer to use callouts.

**Comment by oldjove** [comment]
I'm experiencing this too. It's not all the time though. I have custom callouts that work fine but then others that default to blue. Not sure why this is.

**Comment by valentine195** [comment]
Is it callouts in other windows, or does it happen in the main window?

**Comment by oldjove** [comment]
I've just experienced it in the main window.

**Comment by oldjove** [comment]
@feedhopper @valentine195 , I seem to have worked out the problem. I discovered that the callout wasn't working because I capitalized the "admonition type". Looks like this needs to be lower case for the colour and icon to work properly.

**Comment by sigrunixia** [comment]
This was fixed in #295
