### ISSUE TITLE
Unresolved links rendered incorrectly in Live Preview

### ISSUE THREAD

**Issue by ScottKillen** [javalent/admonitions#254]
When an unresolved link in an admonition is rendered in Live Preview mode during editing, the `.is-unresolved` CSS tag is omitted.

The link is rendered correctly (tag is added) in Read mode.

**Comment by sigrunixia** [comment]
This should be fixed, but I wanted to confirm if you were having any issues still @ScottKillen?

**Comment by ScottKillen** [comment]
Looking good.
