### ISSUE TITLE
Admotion Type cannot have non-ASCII characters in them

### ISSUE THREAD

**Issue by dojje** [javalent/admonitions#258]
I have noticed that the admotion type cannot have non-ASCII characters in them, like åäö.

### only ASCII characters

if i only use **ASCII** characters as the admotion type

![img](https://user-images.githubusercontent.com/50925050/185758463-5f39fdc9-b692-4d3e-84e5-b2083a9b391c.png)

and write this as the admotion:

![img](https://user-images.githubusercontent.com/50925050/185758506-c903c7a3-a74c-41b7-bb22-6b48836c5868.png)

it renders to this:

![img](https://user-images.githubusercontent.com/50925050/185758516-74283758-acf6-4b1f-8449-133d17aa33f8.png)

### non-ASCII charactesrs

but if i have **non-ASCII** characters as the Type

![img](https://user-images.githubusercontent.com/50925050/185758323-d10ed1a8-8e57-4009-89a4-e3067281047c.png)

and write this as the admotion:

![img](https://user-images.githubusercontent.com/50925050/185758360-fddcdff6-fe27-4224-8067-92a800e75a95.png)

it renders to this:

![img](https://user-images.githubusercontent.com/50925050/185758378-7b72c43b-f27c-43b0-ac52-735aa81b8683.png)

**Comment by sigrunixia** [comment]
I can confirm this works in a callout, but does not work in a code block, using the test word "Łemiránin".
