### ISSUE TITLE
[FeatureRequest]  Convert text with Header in Admonition block

### ISSUE THREAD

**Issue by yannick-boehm** [javalent/admonitions#264]
I really love the admonition plug in but I wonder if it would be possible to add the following feature. 

I would like to quick convert a text with a header into an admonition block. Where header is the title and the text would be the body of the admonition block. This would make my work much easier instead of building up the admonition and declare title and admonition layout I could just mark the text and press a shortcut and voila the admonition block is build.

**Comment by valentine195** [comment]
There is a command to convert a selection to an admonition or a callout. Does that work?

**Comment by yannick-boehm** [comment]
None of the standard functionalities would make this possible. 
![image](https://user-images.githubusercontent.com/102553711/194756979-e7af7812-14f3-421c-8531-adb7f341f0e2.png)

I may oversee something but I cannot find a solution for this.
