### ISSUE TITLE
Line breaks not showing correctly in editing preview

### ISSUE THREAD

**Issue by shayyya1** [javalent/admonitions#266]
When writing an admonition, lines seperated by line breaks in the code will not be seperated in the editing preview
![2022-10-15 15_05_20-4 Conditional probability - uni - Obsidian v1 0 0](https://user-images.githubusercontent.com/69038719/195990789-4aecf19e-6e27-4a6a-812c-9ba9c3460351.png)
Results in 
![image](https://user-images.githubusercontent.com/69038719/195990806-0d1fdaec-ca17-4095-b122-254de7391552.png)

**Comment by rotem443** [comment]
Happens to me as well since obsidian 1.0

**Comment by KeiyuKensei** [comment]
Please implement this plugin for version 1.0.0 as soon as possible. Thank you very much

**Comment by nosas** [comment]
This is expected behavior from a markdown point-of-view, but unexpected for Obsidian.

**Comment by rootless69** [comment]
I also have this issue. Seems like removing a selector in assets/main.css is a quick fix:
https://github.com/valentine195/obsidian-admonition/blob/2fb38ccc0b39ada8d3d0a4476e9ff3333c52c3ae/src/assets/main.css#L304-L306

The selector right before can also be removed:
https://github.com/valentine195/obsidian-admonition/blob/2fb38ccc0b39ada8d3d0a4476e9ff3333c52c3ae/src/assets/main.css#L299-L302

This makes line paddings in live preview look almost identical to read mode.

For admonition:
``````````````
`````````ad-info
title: Title
First line.
After a single line break comes a second line.

Two line breaks to a third line, followed by a multi line math block:
$$
z=re^{i \theta}
$$
A line break after the math block comes a fourth line.
Then comes some a long text without line-breaks that repeats. Then comes some a long text without line-breaks that repeats. Then comes some a long text without line-breaks that repeats.

Last line.
`````````
``````````````

Before (Live-Preview):
![image](https://user-images.githubusercontent.com/6492687/199980566-70e0b467-52a6-4001-93e5-160f2bd62510.png)

After (Live-Preview):
![image](https://user-images.githubusercontent.com/6492687/199980798-3803310b-18cb-4295-9f36-d313e4bf99ac.png)

Read Mode:
![image](https://user-images.githubusercontent.com/6492687/199981439-7be550f5-078e-4cc6-81a1-21c6e7006fa7.png)

**Comment by Pedroespecial** [comment]
Wonderful - worked a treat.
For anyone that might be as 'green' as me: the styles.css file was not formatted and was just a mass of text.  I opened it in Visual Studio Code and did a Alt+Shift+F and it all looked nice again and ready to edit :-)

**Comment by valentine195** [comment]
Hi, I’ll remove these lines when I get a chance, but you should not edit plugin css directly. Use a CSS snippet. Otherwise the changes will be overwritten on a plugin update.

**Comment by wlnirvana** [comment]
Look forward to the fix to be released

**Comment by wlnirvana** [comment]
A sample css snippet that worked for me:

```css
/* See https://github.com/valentine195/obsidian-admonition/issues/266#issuecomment-1303527540 */
.is-live-preview .admonition-content > * br {
    display: inline;
}

.is-live-preview .admonition-content > * {
    margin: revert;
}
```

**Comment by sigrunixia** [comment]
Hello everyone.

The PR should fix this issue and the Mathjax issue with spacing as well. If you experience any issues further, please make a new issue.
