### ISSUE TITLE
Can't add custom callout types

### ISSUE THREAD

**Issue by TheChilliPL** [javalent/admonitions#269]
Trying to add a custom callout type does not close the modal.
There are errors showing up in the dev tools:
![image](https://user-images.githubusercontent.com/18823939/200721300-a2456518-8f62-4e42-a184-97ac0f1edc00.png)

**Comment by TheChilliPL** [comment]
Seems to be partially fixed: it does work unless you try creating a callout without an icon. Also, the icon input textbox disappears when unfocusing it without anything typed in

**Comment by sigrunixia** [comment]
@TheChilliPL Can you confirm if you are still experiencing this issue? (Also, make sure you have the most recent update as of a couple days ago).
