### ISSUE TITLE
Admonition graphic bug

### ISSUE THREAD

**Issue by KeiyuKensei** [javalent/admonitions#270]
since I installed obsidian to version 1.0 the graphics of the notes have changed from 

![image](https://user-images.githubusercontent.com/88140674/200888351-e8a9f758-4c09-454b-94d6-0d0d904815da.png)

to 

![image](https://user-images.githubusercontent.com/88140674/200888572-c57e1007-a8db-4276-b241-3ae7d93ee27a.png)

How can i fix this?

**Comment by ATXcoder** [comment]
Looks like this may be the new style that Obsidian renders callouts in:
- https://forum.obsidian.md/t/revert-the-v1-0-callout-changes/45051
- https://forum.obsidian.md/t/why-do-my-callouts-not-have-different-shade-title-line/45458

**Comment by sigrunixia** [comment]
That is correct. If you wish the older style of default callouts, you will need to utilize one of the CSS numerous snippets out there that changes it back. :)
