### ISSUE TITLE
[Feature request] Using tables in callouts

### ISSUE THREAD

**Issue by bingryan** [javalent/admonitions#276]
I found that some form callout is a very good feat.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/41174435/204138934-d3203920-b1eb-4b5e-9eb4-7c910d5af4e7.png">

from [using-ref table](https://swagger.io/docs/specification/using-ref/)

**Comment by sigrunixia** [comment]
Hello @bingryan 

It is not quite clear what you are requesting in this feature. Can you elaborate?

**Comment by bingryan** [comment]
> Hello @bingryan
> 
> It is not quite clear what you are requesting in this feature. Can you elaborate?

include table

**Comment by sigrunixia** [comment]
#163 goes over some of this but I will add more here.

Making those tables right off the bat, without calling in json formatting, is not a realistic use of development time.

So what we suggest is using nested admonition blocks to hold a json code block:

`````yaml
````ad-admonition-name
title: Json test
collapse: Open


```json

Your Json Reference Here

```

````
`````

As this functionality exists and works within Obsidian, I am closing this thread.
