### ISSUE TITLE
【Feature request】enable double click text to edit this block inside the code block

### ISSUE THREAD

**Issue by aiyolo** [javalent/admonitions#278]
I just find that in admonition code block, we must move cursor to the top of code block so that we can click the edit block button.

However, in the native obsidian callout, we can edit the callout just by double clicking the text anywhere inside callout, it is much more convenient. 

So, it would be nice that admonition can support this feature.

**Comment by sigrunixia** [comment]
@aiyolo 
This should be enabled now. Can you confirm?

**Comment by aiyolo** [comment]
Which version do you mean, in the latest version 9.2.3, this problem still exits.

**Comment by sigrunixia** [comment]
It would have been the equivalent of 9.2.3, but looks like we have a regression in the test build as well. I'll see what can be done with this. :)

**Comment by aiyolo** [comment]
Is this issue fixed?
