### ISSUE TITLE
Spacing in edit mode different than reading

### ISSUE THREAD

**Issue by sawft99** [javalent/admonitions#279]
Editing mode has little to no spacing compared to reading mode

# Edit mode
![image](https://user-images.githubusercontent.com/81699231/210612299-74978fc4-5c0f-43ac-ad65-d743653ba05e.png)

# Reading mode
![image](https://user-images.githubusercontent.com/81699231/210612493-0bb3f1b9-1e45-418e-b741-c405eb2d5eb5.png)

**Comment by sigrunixia** [comment]
This is normal behavior between the rendering of reader and live-preview. There is default CSS included to try to increase parity between the two, but In maintaining responsiveness to screen size and different systems, there is only so much that can be done. Individual adjustments will need to be made with your own CSS snippet.
