### ISSUE TITLE
Explicit title invisible when “No Admonition Title by Default” is on

### ISSUE THREAD

**Issue by TheChilliPL** [javalent/admonitions#284]
![image](https://user-images.githubusercontent.com/18823939/213650448-31a39638-4747-4047-82b1-b32bbde9775f.png)

```md
> [!example] This title is invisible
> This content is visible
```

![image](https://user-images.githubusercontent.com/18823939/213650555-8200d76d-1c0a-4a04-a31b-e78f1cb4bdb2.png)

**Comment by sigrunixia** [comment]
Hello,

This is a very belated reply, but that setting _only_ applies to admonition code blocks and not their styled callout counterparts.

**Comment by TheChilliPL** [comment]
Why wouldn't it work with the usual callouts? These also have an optional title, so I'd expect it to work in the exact same way

**Comment by TheChilliPL** [comment]
The issue is still relevant
