### ISSUE TITLE
Publish.js seems to not be working

### ISSUE THREAD

**Issue by sigrunixia** [javalent/admonitions#294]
Not sure if it's a wonky site thing, or an issue with the publish code, but putting this here as I know you have a lot on your plate. The publish.js being exported is currently not working on the dev documentation site, so I can assume if it's not just an _us_ issue, then it may be affecting others.

It's not critical* because the callouts still work, so those will do in the meantime.

**Comment by valentine195** [comment]
Yeah, I think it would be better to remove this and recommend using callouts if publish support is needed.

**Comment by sigrunixia** [comment]
That works for me. :)
