### ISSUE TITLE
custom callouts rendered to probably some default value

### ISSUE THREAD

**Issue by henryZrncik** [javalent/admonitions#301]
i have my own callout specified using UI in Obsidian. 

when i try to use it it seems like following: 
(all of these are written using callouts):
first one is provided by you which renders correctly, 
second one and third one are mine, they are supposed to be with different icon and colour (same problems with rest of my custom admonitions). 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/40673682/233805642-5b208baf-b06f-40fb-8376-46aec77f3303.png">

I would normally avoid using callouts, ut the thing is that if i use default way, i.e., ``` ```  in that case problem is that although it renders correctly, links in graph view are not showed in case i have link to some other part of notes.

**Comment by valentine195** [comment]
Can you try using lowercase? Just a thought

**Comment by henryZrncik** [comment]
thank you, refactor to snake case seem solve it almost perfectly.
