### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Corkers7** [javalent/admonitions#313]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I expect the admonition to just be a standard box, being much smaller than it is here without all the empty space or the backlink section (not used obsidian in a long time and don't know how to undo this as makes it very clunky and visually unappealing not being able to disable this)

### Current behaviour

![image](https://github.com/javalent/admonitions/assets/138039834/537895e4-8d57-453c-b41c-7102e0ae5ed5)
![image](https://github.com/javalent/admonitions/assets/138039834/2780bf83-1130-4f55-b2ed-7665f1dcd3c7)

### Reproduction

```ad-note
XYZ
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

9.3.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

I have no experience with cod - but I imagine this isn't something everyone is experiencing so im hoping there is a simple fix i have just missed

**Comment by valentine195** [comment]
Neither the empty space nor the backlink section is coming from the Admonitions plugin. The admonition is just the region with the black background.
