### ISSUE TITLE
Cannot update or install on Android 11🐞

### ISSUE THREAD

**Issue by merlinuwe** [javalent/admonitions#321]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I want to update to the latest release 10. This did not work so I uninstalled 9.3.3, restarted Obsidian and wanted to install Release 10. Does not work on Xiaomi Poco X3 Pro.

### Current behaviour

I cannot install the plugin

### Reproduction

Easy to reproduce

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.4.6 (105) 

### Plugin Version

10.0.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Can you try again?

**Comment by merlinuwe** [comment]
solved ;-)

Thank you very much for your great plugin.
