### ISSUE TITLE
🐞 Internal links in the Admonition are no longer clickable.

### ISSUE THREAD

**Issue by Ha-gi-wa-ra** [javalent/admonitions#325]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Clicking on an internal link within Admonition will take me to the linked page like Callout.

### Current behaviour

When clicking on an internal link in Admonition, it switches to edit mode and the link does not work.

### Reproduction

1. Launch Obsidian in Live preview mode.
2. Create an Admonition and include a sentence containing an internal link.
3. Attempt to click on the rendered link.

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.4.13 and 1.4.13

### Plugin Version

10.1.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Whoops, this was a side effect of fixing #278

**Comment by Lucifer-Clegg** [comment]
i have the same behavior.
--
Obsidian Version Check
1.4.13 
[x] Windows

Plugin Version
10.1.0

I installed the previous verion (10.0.2)
and the issue wont occur.

**Comment by valentine195** [comment]
This should be fixed in #326
