### ISSUE TITLE
Unresolved internal links don't look different

### ISSUE THREAD

**Issue by davidkopp** [javalent/admonitions#328]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Internal links that are not resolvable, e.g. the linked note does not exist yet, should look differently in comparison to internal links that are resolvable. In a normal text and within an Obsidian callout this is the case, but not within an admonition.

### Current behaviour

Comparison Callout vs. Admonition:

![image](https://github.com/javalent/admonitions/assets/7796322/4de1ff0b-09cd-4ec6-9c84-26ccf2f6d480)

### Reproduction

Used markdown:

~~~plain
> [!info] Callout
> 
> [[note does exist]]
> [[note does not exist yet]]

```ad-info
title: Admonition

[[note does exist]]
[[note does not exist yet]] 
```
~~~

The note with the name "note does exist" was created for this test.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

10.1.1

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

### Possible solution

When I add the class `is-unresolved` to the link in the admonition with the help of the developer console the link does get formatted correctly.

Potential fix:
Add a check if the internal links inside an admonition are resolvable before the admonition gets rendered. If not, add the class `is-unresolved` to it.

**Comment by valentine195** [comment]
This is unfortunately an issue from Obsidian. Admonitions does not do anything special with links, it just provides the content to Obsidian's markdown renderer and displays what it is given. It looks like the renderer in live preview is not setting the links to unresolved (oddly enough it looks like it does in reading mode).

I'll talk to the Obsidian devs to see what's going on, but I'm going to close this issue.
