### ISSUE TITLE
🐞 Commands to Collapse and Open Admonition in Note not working

### ISSUE THREAD

**Issue by VerAn1015** [javalent/admonitions#329]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I expect collapsible admonitions to collapse or open upon clicking command in command palette. 

### Current behaviour

Nothing happens upon clicking the commands in command palette.

### Reproduction

1. Open sandbox vault, install and enable plugin.
2. Create collapsible admonitions.
3. Open command palette, search and click Collapse Admonitions in Note or Open Admonitions in Note.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16 and 1.4.16

### Plugin Version

10.1.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
I believe this was closed with release v10.1.2
