### ISSUE TITLE
Admonition Type Drop Down List Is Not Availabe

### ISSUE THREAD

**Issue by EthanDow** [javalent/admonitions#342]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The drop-down list should be available 

### Current behaviour

When trying to create an admonition, you are usually asked to choose an admonition type from a drop down list but the list is not available anymore. I have attached a video to this for demo

https://github.com/javalent/admonitions/assets/38364454/cb968ede-3c85-435c-ad2d-a45cfe831662

### Reproduction

Refer to the video

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.6.1

### Plugin Version

10.3.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

N/A

**Comment by albertoloscerritos** [comment]
same here on windows 11 obsidian v 1.6.1

**Comment by Smitty010** [comment]
I think this is related to #343
