### ISSUE TITLE
🐞 Default Admonition Types missing from latest update

### ISSUE THREAD

**Issue by MyHeadHurtsNow** [javalent/admonitions#343]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Default types should have been in the drop down menu and the desired default displayed for selection (e.g. Important) selected when first 3 or characters entered by user

### Current behaviour

Upon using the menu short cut to enter an admonition, the Admonition menu open as normal. But as I typed in the Important type required, the plug in returned an error message stating no such admonition exists. 

### Reproduction

1. Select Admonition icon ftom Ribbon Menu.
2. Enter "imp" in Admonition Type selection entry box.
3. You will receive error msg "No such admonition exists

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.5.12 (134)

### Plugin Version

10.3.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by n30s4m** [comment]
The same occurs for me, through the activation for insertion by means of shortcut. No Admonition appears, neither the patterns nor those created by the user. I tried to disable the shortcut and create again, opened and closed Obsidian (W11) but did not return. I also tried to export the existing ones and import again, but it didn't work either.

**Comment by martin-arg** [comment]
I have the same problem in windows 10, in several computers.

**Comment by albertoloscerritos** [comment]
same here

**Comment by Smitty010** [comment]
Windows 11, latest obsidian, same here

**Comment by Manu3232** [comment]
same, no more dropdown in the menu

![image](https://github.com/javalent/admonitions/assets/168284584/7c0104b8-a89b-4dab-b9a5-58e7a67cdcde)

**Comment by MyHeadHurtsNow** [comment]
Thank-you for the fix and all your hard work getting and keeping Admonitions running. It's the first and only issue I've ever had with it. And that speaks to your diligence and skills.
