### ISSUE TITLE
Links inside admonitions not showing up in Graph View or Backlinks

### ISSUE THREAD

**Issue by vi-cat** [javalent/admonitions#350]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Links inside an admonition should work like any link - the connection shows up in the graph view and in backlinks.

### Current behaviour

The links inside of admonitions do not show up in graph views or backlinks, as if these connections do not exist.

### Reproduction

```ad-personality
title: Example admonition
- Lorem ipsum [[Link A]]
- Lorem ipsum [[Link B]]
```

The links to [[Link A]] or [[Link B]] work, (as in I can click it and it will take me to the page), but it doesn't show up in Graph View or as a Backlink.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.4.13

### Plugin Version

10.3.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by HugleDong** [comment]
Another issue is that if I change the file name or change the location, the links placed in the admonition will not be updated.

For example:

```ad-bug
title: Link to another note

![[note-1]]
```

if rename the `note-1` to `note-2`, the name in the ad-code is still `note-1`, which would lost the connection with the note-2

**Comment by valentine195** [comment]
This is a known issue with code blocks. Use callouts if you need link metadata interactions.
